apiVersion: v1
kind: Service
metadata:
  name: hotel-booking-service
  namespace: hotel-booking
  labels:
    app: hotel-booking
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"               # Use Network Load Balancer (fast & stable)
    service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing" # Ensure it's public
    service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
spec:
  selector:
    app: hotel-booking
    version: blue  # This will switch between blue/green
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
