apiVersion: v1
kind: Service
metadata:
  name: hotel-booking-system
  namespace: hotel-booking
  labels:
    app: hotel-booking-system
spec:
  selector:
    app: hotel-booking-system
    version: blue
  ports:
    - port: 80
      targetPort: 8080
  type: LoadBalancer
