apiVersion: v1
kind: Service
metadata:
  name: hotel-booking-system
  namespace: hotel-booking
  labels:
    app: hotel-booking-system
spec:
  selector:
    app: hotel-booking-system
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      protocol: TCP
  type: ClusterIP
