apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-config
  namespace: hotel-booking
data:
  init.sql: |
    CREATE DATABASE IF NOT EXISTS hotel_booking_system;
    CREATE USER IF NOT EXISTS 'hotel_user'@'%' IDENTIFIED BY 'Hotel@123';
    GRANT ALL PRIVILEGES ON hotel_booking_system.* TO 'hotel_user'@'%';
    FLUSH PRIVILEGES;
    
    USE hotel_booking_system;