apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: hotel-booking
type: Opaque
data:
  # echo -n 'Shanu@9090!' | base64
  root-password: WW91clNlY3VyZU15U1FMUm9vdFBhc3N3b3JkMTIzIQ==
  # echo -n 'hotel_user' | base64
  username: aG90ZWxfdXNlcg==
  # echo -n 'Hotel@123' | base64
  password: SG90ZWxAMTIz